backend:
  name: git-gateway
  repo: tjscivsav/madison_brown
  branch: main
media_folder: src/images/uploads
collections:
  - name: socialLinks
    label: Social Links
    files:
      - label: Links
        name: socialLinks
        file: site/socialLinks.json
        fields:
          - { label: Twitter, name: twitter, widget: string }
          - { label: Facebook, name: facebook, widget: string }
          - { label: Instagram, name: instagram, widget: string }
          - { label: TikTok, name: tiktok, widget: string }
