backend:
  name: git-gateway
  repo: tjscivsav/madison_brown
  branch: develop
media_folder: src/images/uploads

collections:
  - name: socialLinks
    label: Social Links
    files:
      - label: Links
        name: socialLinks
        file: site/socialLinks.md
        fields:
          - { label: Twitter, name: twitter, widget: string }
          - { label: Facebook, name: facebook, widget: string }
          - { label: Instagram, name: instagram, widget: string }
          - { label: TikTok, name: tiktok, widget: string }
  - name: home
    label: Home Page
    files:
      - label: Content
        name: content
        file: site/home.md
        fields:
          - {
              label: SEO Title,
              name: seoTitle,
              widget: string,
              required: false,
            }
          - {
              label: SEO Description,
              name: seoDescription,
              widget: string,
              required: false,
            }
          - { label: Heading, name: title, widget: string, required: false }
          - { label: Desciption, name: desc, widget: string, required: false }
          - { label: Backgroud Image, name: bg_img, widget: image }
          - { label: Ice cream Image, name: front_img, widget: image }
          - { label: Poster Title, name: poster_title, widget: string }
  - name: about
    label: About Page
    files:
      - label: Content
        name: content
        file: site/about.md
        fields:
          - {
              label: SEO Title,
              name: seoTitle,
              widget: string,
              required: false,
            }
          - {
              label: SEO Description,
              name: seoDescription,
              widget: string,
              required: false,
            }
          - { label: Paragraph, name: para1, widget: string, required: false }
          - { label: Paragraph, name: para2, widget: string, required: false }
  - name: products
    label: Products
    files:
      - label: Content
        name: content
        file: site/products.md
        fields:
          - label: Product List
            name: products
            widget: list
            fields:
              - { label: Ice Cream, name: img, widget: image }
              - { label: Frame, name: frame, widget: image, required: false }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: desc, widget: string }
              - { label: Background Color, name: btn_color, widget: string }
              - { label: ID, name: id, widget: string }
  - name: shops
    label: Shops
    files:
      - label: Content
        name: content
        file: site/shops.md
        fields:
          - label: Shop List
            name: shops
            widget: list
            fields:
              - { label: Location, name: location, widget: string }
              - {
                  label: Upcoming?,
                  name: upcoming,
                  widget: string,
                  required: false,
                }
              - { label: Image, name: img, widget: image }
